### ISSUE TITLE
Change OR override from Cd to drag force

### ISSUE THREAD

**Issue by Joe-Joe-Joe-Joe** [waterloo-rocketry/or-airbrake-plugin#4]
@celery6 tracking this for posterity

As the simulation procedure has matured, the Ansys interface is now a set of fitted drag curves at fixed airbrake extension amounts, rather than cd curves. This has been implemented for trajectory prediction, but the override for OR itself currently requires to go backwards to Cd. Ideally we calculate drag for OR the same way we do it for the controller prediction step.

this is the offending code, ideally it edits drag directly instead:
```// Calculate and override cd. No coast check here since it's done in preStep
		if (!Double.isNaN(airbrakeExt)) {
			double cd = TrajectoryPrediction.interpolate_cd(airbrakeExt, velocity, altitude);
			if (cd > 0) forces.setCDaxial(cd);
			else forces.setCDaxial(0);
			
		}```

**Comment by patrick-gu** [comment]
Resolved in #12
