### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by Joe-Joe-Joe-Joe** [waterloo-rocketry/or-airbrake-plugin#5]
Currently, the plugin interface only lets you swap to and from the PID controller. The target apogee and controller gains are compile-time constants, which makes tuning them a giga pain in the ass. It would be nice to have fields for target apogee, Kp, Ti, Td, and maybe one to turn off the controller entirely.

**Comment by celery6** [comment]
I'll add input boxes for pid, and target apogee.

I couldn't figure out a good way to have more than 2 modes (PID/AlwaysOn). However, can add an input for % extension in AlwaysOn mode so it can just be set to 0% to be always off.
